apiVersion: v2
actions:
  - name: "Run k6"
    events:
      - name: "sh.keptn.event.test.triggered"
    tasks:
      - name: "Launching k6"
        image: "alpine:3.16.2"
        cmd: ["sleep"]
        args: ["10"]
      - name: "Run k6 for Fibonacci"
        files:
          - /k6
        image: "loadimpact/k6:0.39.0"
        cmd: ["k6"]
        # ToDo: set the correct stage
        args: ["run", "-e", "BASE_URL=fibonacci.fibonacci-production.svc.cluster.local:80", "--duration", "30s", "--vus", "10", "/keptn/k6/calculate.js"]
