apiVersion: spec.keptn.sh/0.2.2
kind: Shipyard
metadata:
  name: "fibonacci"
spec:
  stages:
  - name: staging
    sequences:
    - name: delivery
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: user_managed
      - name: test
        properties:
          teststrategy: performance
      #- name: evaluation
      #- name: approval
      #  properties:
      #    pass: automatic
      #    warning: automatic
      - name: release
  - name: production
    sequences:
    - name: delivery
      triggeredOn:
      - event: staging.delivery.finished
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: user_managed
      - name: test
        properties:
          teststrategy: performance
      #- name: evaluation
      #- name: approval
      #  properties:
      #    pass: automatic
      #    warning: automatic
      - name: release